security:
  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
      algorithm: bcrypt
      cost: 13

  providers:
    app_user_provider:
      entity:
        class: App\Entity\User
        property: username

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    role_select:
      pattern: ^/role-select$
      security: false

    main:
      lazy: true
      provider: app_user_provider
      custom_authenticator: App\Security\AppAuthenticator
      logout:
        path: app_logout
        target: app_role_select
        delete_cookies:
          - PHPSESSID
      remember_me:
        secret: "%kernel.secret%"
        lifetime: 604800
        path: /
        always_remember_me: false

  access_control:
    - { path: ^/login, roles: PUBLIC_ACCESS }
    - { path: ^/role-select, roles: PUBLIC_ACCESS }
    - { path: ^/password-recovery, roles: PUBLIC_ACCESS }
    - { path: ^/password-reset, roles: PUBLIC_ACCESS }
    - { path: ^/admin, roles: ROLE_SUPER_ADMIN }
    - { path: ^/settings/admin, roles: ROLE_SUPER_ADMIN }
    - { path: ^/settings/profile, roles: IS_AUTHENTICATED_FULLY }
    - { path: ^/api/, roles: ROLE_SUPER_ADMIN|ROLE_SUB_ADMIN }
    - { path: ^/dashboard/super-admin, roles: ROLE_SUPER_ADMIN }
    - { path: ^/dashboard/sub-admin, roles: ROLE_SUB_ADMIN }
    - { path: ^/dashboard/manager, roles: ROLE_MANAGER }
    - { path: ^/dashboard/staff, roles: ROLE_STAFF }
    - { path: ^/, roles: IS_AUTHENTICATED_FULLY }
